import localFont from "next/font/local";
import Script from "next/script";
import "./globals.css";
import Header from "@/component/MainHeader";
import "../assets/css/bootstrap.min.css"; // First import Bootstrap
import "../assets/css/style.css"; // Then import your global styles
import "../assets/css/responsive.css"; // Finally, import the responsive styles
import "../assets/css/swiper-bundle.min.css";
import Footer from "@/component/Footer";
import Link from "next/link";

const geistSans = localFont({
  src: "../fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "../fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body id="body" className={`${geistSans.variable} ${geistMono.variable}`}>
        <div className="cursor"></div>
        {/* Local Scripts */}
        <Script src="/js/popper.min.js" strategy="lazyOnload" />
        <Script src="/js/bootstrap.min.js" strategy="lazyOnload" />{" "}
        <Script src="/js/main.js" strategy="lazyOnload" />
        <Script src="/js/masonry.pkgd.min.js" strategy="lazyOnload" />
        <Script
          src="https://cdn.jsdelivr.net/npm/swiper@latest/swiper-bundle.min.js"
          strategy="beforeInteractive" // Ensure Swiper loads before your script
        />
        <Script
          src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"
          strategy="beforeInteractive" // Ensure jQuery loads before your script
        />
        {/* Main Script */}
        {/* HEADER --------------------- */}
        <Header />
        {children}
        {/* FOOTER --------------------- */}
        <Footer />
        {/* External Scripts */}
        <Script
          src="https://cdnjs.cloudflare.com/ajax/libs/gsap/3.12.5/gsap.min.js"
          integrity="sha512-7eHRwcbYkK4d9g/6tD/mhkf++eoTHwpNM9woBxtPUBWm67zeAfFC+HrdoE2GanKeocly/VxeLvIqwvCdk7qScg=="
          crossOrigin="anonymous"
          referrerPolicy="no-referrer"
          strategy="beforeInteractive"
        />
        <Script
          src="https://cdnjs.cloudflare.com/ajax/libs/gsap/3.12.5/ScrollTrigger.min.js"
          integrity="sha512-onMTRKJBKz8M1TnqqDuGBlowlH0ohFzMXYRNebz+yOcc5TQr/zAKsthzhuv0hiyUKEiQEQXEynnXCvNTOk50dg=="
          crossOrigin="anonymous"
          referrerPolicy="no-referrer"
          strategy="beforeInteractive"
        />
        <Script
          src="https://cdnjs.cloudflare.com/ajax/libs/gsap/3.11.2/TextPlugin.min.js"
          strategy="beforeInteractive"
        />
        <Script
          src="https://cdnjs.cloudflare.com/ajax/libs/gsap/3.11.0/SplitText.min.js"
          strategy="beforeInteractive"
        />
        {/* jQuery and CircleType */}
        <Script
          src="https://code.jquery.com/jquery-3.6.0.min.js"
          strategy="lazyOnload"
        />
        <Script
          src="https://cdn.jsdelivr.net/npm/circletype@2.3.0/dist/circletype.min.js"
          strategy="lazyOnload"
        />
      </body>
    </html>
  );
}
